openapi: 3.0.3
info:
  title: Transport and External Delivery Services 
  description: "This document is a draft api between the transport system  and external delivery services. <br> The api describes: <ul><li> How to query and filter existing deliveries </li><li>How to upsert deliveries</li></ul><i>The api is maintained by [ElderByte AG](http://elderbyte.com).</i>"
  version: 0.0.2
tags:
  - name: deliveries
    description: Upserting, deleting and requesting state about deliveries.
paths:
#################################
###################### DELIVERIES
#################################
  /deliveries:
    #################################
    ################## DELIVERIES GET
    #################################
    get:
      tags:
        - deliveries
      summary: Query and filter deliveries
      parameters:
        - name: customerId
          in: header
          description: Customer identification.
          required: true
          schema:
            type: string
        - name: stateChangedSince
          in: query
          description: Filters by deliveries which changed their current state since 'stateChangedSince'.
          required: false
          schema:
            type: string
        - name: states
          in: query
          description: Filters by deliveries with matching state.
          required: false
          schema:
            type: array
            items:
              type: string
        - name: property1
          in: query
          description: Filters by property1.
          required: false
          schema:
            type: boolean
        - name: property2
          in: query
          description: Filters by property2.
          required: false
          schema:
            type: boolean
        - name: propertyN
          in: query
          description: Filters by propertyN.
          required: false
          schema:
            type: boolean
      responses:
        '200':
          description: All deliveries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Delivery'
  '/deliveries/{deliveryId}':
    get:
      tags:
        - deliveries
      summary: Query a specific delivery
      parameters:
        - name: customerId
          in: header
          description: Customer identification
          required: true
          schema:
            type: string
        - name: deliveryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A delivery
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '404':
          description: Delivery not found
    #################################
    ################## DELIVERIES PUT
    #################################
    put:
      tags:
        - deliveries
      summary: 'Upsert a delivery: Update an existing delivery order, create a non-existing delivery order'
      parameters:
        - name: customerId
          in: header
          description: Customer identification
          required: true
          schema:
            type: string
        - name: deliveryId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: The delivery to upsert
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryOrder'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
#################################
########### APPLY GLOBAL SECURITY
#################################
security: 
 - CarrierAPIKey: []
#################################
###################### COMPONENTS
#################################
components:
  #################################
  ## DEFINITION OF SECURITY SCHEMES
  #################################
  securitySchemes:
    CarrierAPIKey:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    #################################
    #### DEFINITION OF DELIVERY ORDER
    #################################
    DeliveryOrder:
      type: object
      required: 
        - id
        - state
        - deliveryTimeFrame
        - issuerContact
        - dropoffAddress
        - dropoffContact
        - pickupAddress
        - pickupContact
      properties:
        id:
          type: string
        state:
          $ref: '#/components/schemas/DeliveryOrderState'
        deliveryTimeFrame:
          type: string
          description: ISO interval (Instant from / Instant to)
        totalWeight:
          $ref: '#/components/schemas/Quantity'
          properties:
            value:
              type: string
            unit:
              type: string
        packages:
          type: array
          items:
            $ref: '#/components/schemas/Package'
        properties:
          type: object
          properties:
            property1:
              type: string
            property2:
              type: string
            propertyN:
              type: string
        note:
          type: string
        issuerContact:
          $ref: '#/components/schemas/Contact'
        dropoffAddress:
          $ref: '#/components/schemas/Address'
        dropoffContact:
          $ref: '#/components/schemas/Contact'
        pickupAddress:
          $ref: '#/components/schemas/Address'
        pickupContact:
          $ref: '#/components/schemas/Contact'
    #################################
    ########## DEFINITION OF PACKAGES
    #################################
    Package:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          weight:
            $ref: '#/components/schemas/Quantity'
          dimensions:
            $ref: '#/components/schemas/Dimension'
          items:
            type: array
            items:
              type: string
    #################################
    ########## DEFINITION OF DELIVERY
    #################################
    Delivery:
      type: object
      required: 
        - id
        - state
        - deliveryOrder
      properties:
        id:
          type: string
        state:
          $ref: '#/components/schemas/DeliveryState'
        stateHistory:
          type: array
          items:
            type: object
            properties:
              state:
                $ref: '#/components/schemas/DeliveryState'
              stateTimestamp:
                type: string
        estimatedDeliveryTimeFrame:
          type: string
          description: ISO interval (Instant from / Instant to)
        note:
          type: string
        printLabel:
          type: object
          properties:
            required:
              type: boolean
            data:
              $ref: '#/components/schemas/PrintLabel'
        deliveryOrder:
          $ref: '#/components/schemas/DeliveryOrder'
    #################################
    ## DEFINITION OF PRINT LABEL DATA
    #################################
    PrintLabel:
      type: object
      properties:
        field1:
          type: string
        field2:
          type: string
        field3:
          type: string
    #################################
    ##### DEFINITION OF DELIVERY STATE
    #################################
    DeliveryState:
      type: string
      enum:
        - PREVIEW
        - CONFIRMED
        - CANCELED
        - IN_PROGRESS
        - COMPLETED
        - FAILED
    #################################
    #DEFINITION OF DELIVERY ORDER STATE
    #################################
    DeliveryOrderState:
      type: string
      enum:
        - PREVIEW
        - COMPLETED
        - CANCELED
    #################################
    ########### DEFINITION OF ADDRESS
    #################################
    Address:
      type: object
      required: 
        - street
        - zip
        - city
      properties:
            name:
              type: string
            street:
              type: string
            poBox:
              type: string
            additive:
              type: string
            city:
              type: string
            zip:
              type: string
            state:
              type: string
            country:
              type: string
    #################################
    ########### DEFINITION OF CONTACT
    #################################
    Contact:
      type: object
      required: 
        - lastName
        - phones
      properties:
        title:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        email:
          type: string
        phones:
          type: array
          items:
            type: string
    #################################
    ######### DEFINITION OF DIMENSION
    #################################
    Dimension:
      type: object
      required: 
        - width
        - height
        - length
        - unit
      properties:
        width:
          type: string
        height: 
          type: string
        length:
          type: string
        unit:
          type: string
    #################################
    ########### DEFINITION OF Quantity
    #################################
    Quantity:
      type: object
      required: 
        - value
        - unit
      properties:
        value:
          type: string
        unit:
          type: string
          
        
            
          
